# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

k_means <- function(clusters, tf_idf) {
    .Call('TFIDF_k_means', PACKAGE = 'TFIDF', clusters, tf_idf)
}

tf_idf <- function(raw_frequency, tid) {
    .Call('TFIDF_tf_idf', PACKAGE = 'TFIDF', raw_frequency, tid)
}

